version: 2.1
general:
  branches:
    only:
      - testUnit

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:12.14.1 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
  test:
    docker:
      - image: cimg/node:12.14.1 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: npm install --save
      - run: npm audit fix
      - run: npm test

  deploy:
    docker:
      - image: cimg/node:12.14.1 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: sudo sh -c "curl -s https://cli.nr-ext.net/installer.sh | bash"
      - run: nr1 --version
      - run: nr1 profiles:add --name ${NR_PROFILE_NAME} --api-key ${NR_API_KEY} --region us
      - run: nr1 nerdpack:publish --channel DEV --force
      - run: nr1 nerdpack:subscribe -c DEV

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
